sector_tuner:
  ros__parameters:
    global_limit: 0.5
    n_sectors: 5
    Sector0:
      start: 0
      end: 189
      scaling: 0.5
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 190
      end: 251
      scaling: 0.5
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 252
      end: 329
      scaling: 0.5
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 330
      end: 367
      scaling: 0.5
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 368
      end: 547
      scaling: 0.5
      only_FTG: false
      no_FTG: false
